BachHoaMint/Controllers/HoaDonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BachHoaMint.Models;

namespace BachHoaMint.Controllers
{
    public class HoaDonController : Controller
    {
        private QLBHEntities db = new QLBHEntities();

        // GET: HoaDon
        public ActionResult Index()
        {
            var hoaDons = db.HoaDons.Include(h => h.KhachHang).Include(h => h.Nhanvien);
            return View(hoaDons.ToList());
        }

        // GET: HoaDon/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HoaDon hoaDon = db.HoaDons.Find(id);
            if (hoaDon == null)
            {
                return HttpNotFound();
            }
            return View(hoaDon);
        }

        // GET: HoaDon/Create
        public ActionResult Create()
        {
            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "TenKH");
            ViewBag.MaNV = new SelectList(db.Nhanviens, "MaNV", "HoNV");
            return View();
        }

        // POST: HoaDon/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaHD,MaKH,MaNV,NgayLapHD,NgayGiaoHang")] HoaDon hoaDon)
        {
            if (ModelState.IsValid)
            {
                db.HoaDons.Add(hoaDon);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "TenKH", hoaDon.MaKH);
            ViewBag.MaNV = new SelectList(db.Nhanviens, "MaNV", "HoNV", hoaDon.MaNV);
            return View(hoaDon);
        }

        // GET: HoaDon/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HoaDon hoaDon = db.HoaDons.Find(id);
            if (hoaDon == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "TenKH", hoaDon.MaKH);
            ViewBag.MaNV = new SelectList(db.Nhanviens, "MaNV", "HoNV", hoaDon.MaNV);
            return View(hoaDon);
        }

        // POST: HoaDon/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaHD,MaKH,MaNV,NgayLapHD,NgayGiaoHang")] HoaDon hoaDon)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hoaDon).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "TenKH", hoaDon.MaKH);
            ViewBag.MaNV = new SelectList(db.Nhanviens, "MaNV", "HoNV", hoaDon.MaNV);
            return View(hoaDon);
        }

        // GET: HoaDon/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HoaDon hoaDon = db.HoaDons.Find(id);
            if (hoaDon == null)
            {
                return HttpNotFound();
            }
            return View(hoaDon);
        }

        // POST: HoaDon/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            HoaDon hoaDon = db.HoaDons.Find(id);
            db.HoaDons.Remove(hoaDon);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BachHoaMint/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BachHoaMint.Models;
using System.Collections;

namespace BachHoaMint.Controllers
{
    public class MenuController : Controller
    {
        private QLBHEntities db = new QLBHEntities();
        // GET: Menu
        public ActionResult Index()
        {
            var loaisp = db.LoaiSPs.ToList();
            Hashtable arrLoaiSP = new Hashtable();
            foreach(var item in loaisp)
            {
                arrLoaiSP.Add(item.MaLoaiSP, item.TenLoaiSP);
            }
            ViewBag.LoaiSP = arrLoaiSP;
            return PartialView("Index");
        }
    }
}

BachHoaMint/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cooky Beauty</title>
    <link rel="shortcut icon" href="~/myicon.ico" type="image/x-icon" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body style="background-color: #9ae5e5">
        <div class="navbar navbar-fixed-top" style="background-color: #f2baba">
            <div class="container" style="background-color: lightpink">
                <div class="navbar-header">
                    @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>*@
                    <img src="~/logo/trangchu.png" alt="logo" style="width:50px;">
                    @Html.ActionLink("Trang chủ ☜", "Index", "Home", new { area = "" },
                                    new { @class = "navbar-header" })
                </div>
                <div class="navbar-inverse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Loại sản phẩm
                                <span class="caret"></span>
                            </a>
                            @{ Html.RenderAction("Index", "Menu"); }
                        </li>

                        @if (Request.IsAuthenticated && User.IsInRole("Admin") || User.IsInRole("Master"))
                        {
                            <li>@Html.ActionLink("Sản phẩm", "Index", "SanPham")</li>
                            <li>@Html.ActionLink("Khách hàng", "Index", "KhachHang")</li>
                            <li>@Html.ActionLink("Hoá đơn", "Index", "HoaDon")</li>
                            if (User.IsInRole("Admin"))
                            {
                                <li>@Html.ActionLink("Nhân viên", "Index", "NhanVien")</li>
                                <li>@Html.ActionLink("Quản trị", "Index", "Admin")</li>
                            }
                        }
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Cooky Beauty</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>