BachHoaMint/Models/HoaDon.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BachHoaMint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public string MaHD { get; set; }
        public string MaKH { get; set; }
        public Nullable<int> MaNV { get; set; }
        public System.DateTime NgayLapHD { get; set; }
        public System.DateTime NgayGiaoHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual Nhanvien Nhanvien { get; set; }
    }
}

BachHoaMint/Controllers/CTHDController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BachHoaMint.Models;

namespace BachHoaMint.Controllers
{
    public class CTHDController : Controller
    {
        private QLBHEntities db = new QLBHEntities();

        // GET: CTHD
        public ActionResult Index(string mahd)
        {
            List<KhachHang> khachhang = db.KhachHangs.ToList();
            List<HoaDon> hoadon = db.HoaDons.ToList();
            List<SanPham> sanpham = db.SanPhams.ToList();
            List<CTHD> cthd = db.CTHDs.ToList();
            var main = from h in hoadon
                       join k in khachhang on h.MaKH equals k.MaKH
                       where h.MaHD == mahd
                       select new ViewModel
                       {
                           hoadon = h,
                           khachhang = k
                       };
            var sub = from c in cthd
                      join s in sanpham on c.MaSP equals s.MaSP
                      where c.MaHD == mahd
                      select new ViewModel
                      {
                          cthd = c,
                          sanpham = s,
                          Thanhtien = Convert.ToDouble(c.DongiaBan * c.Soluong)
                      };
            ViewBag.Main = main;
            ViewBag.Sub = sub;
            return View();

            var cTHDs = db.CTHDs.Include(c => c.HoaDon).Include(c => c.SanPham);
            return View(cTHDs.ToList());
        }

        // GET: CTHD/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CTHD cTHD = db.CTHDs.Find(id);
            if (cTHD == null)
            {
                return HttpNotFound();
            }
            return View(cTHD);
        }

        // GET: CTHD/Create
        public ActionResult Create()
        {
            ViewBag.MaHD = new SelectList(db.HoaDons, "MaHD", "MaKH");
            ViewBag.MaSP = new SelectList(db.SanPhams, "MaSP", "TenSP");
            return View();
        }

        // POST: CTHD/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaHD,MaSP,Soluong,DongiaBan,Giamgia")] CTHD cTHD)
        {
            if (ModelState.IsValid)
            {
                db.CTHDs.Add(cTHD);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaHD = new SelectList(db.HoaDons, "MaHD", "MaKH", cTHD.MaHD);
            ViewBag.MaSP = new SelectList(db.SanPhams, "MaSP", "TenSP", cTHD.MaSP);
            return View(cTHD);
        }

        // GET: CTHD/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CTHD cTHD = db.CTHDs.Find(id);
            if (cTHD == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaHD = new SelectList(db.HoaDons, "MaHD", "MaKH", cTHD.MaHD);
            ViewBag.MaSP = new SelectList(db.SanPhams, "MaSP", "TenSP", cTHD.MaSP);
            return View(cTHD);
        }

        // POST: CTHD/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaHD,MaSP,Soluong,DongiaBan,Giamgia")] CTHD cTHD)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cTHD).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaHD = new SelectList(db.HoaDons, "MaHD", "MaKH", cTHD.MaHD);
            ViewBag.MaSP = new SelectList(db.SanPhams, "MaSP", "TenSP", cTHD.MaSP);
            return View(cTHD);
        }

        // GET: CTHD/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CTHD cTHD = db.CTHDs.Find(id);
            if (cTHD == null)
            {
                return HttpNotFound();
            }
            return View(cTHD);
        }

        // POST: CTHD/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            CTHD cTHD = db.CTHDs.Find(id);
            db.CTHDs.Remove(cTHD);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BachHoaMint/Controllers/HoaDonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BachHoaMint.Models;

namespace BachHoaMint.Controllers
{
    public class HoaDonController : Controller
    {
        private QLBHEntities db = new QLBHEntities();

        // GET: HoaDon
        public ActionResult Index()
        {
            var hoaDons = db.HoaDons.Include(h => h.KhachHang).Include(h => h.Nhanvien);
            return View(hoaDons.ToList());
        }

        // GET: HoaDon/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HoaDon hoaDon = db.HoaDons.Find(id);
            if (hoaDon == null)
            {
                return HttpNotFound();
            }
            return View(hoaDon);
        }

        // GET: HoaDon/Create
        public ActionResult Create()
        {
            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "TenKH");
            ViewBag.MaNV = new SelectList(db.Nhanviens, "MaNV", "HoNV");
            return View();
        }

        // POST: HoaDon/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaHD,MaKH,MaNV,NgayLapHD,NgayGiaoHang")] HoaDon hoaDon)
        {
            if (ModelState.IsValid)
            {
                db.HoaDons.Add(hoaDon);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "TenKH", hoaDon.MaKH);
            ViewBag.MaNV = new SelectList(db.Nhanviens, "MaNV", "HoNV", hoaDon.MaNV);
            return View(hoaDon);
        }

        // GET: HoaDon/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HoaDon hoaDon = db.HoaDons.Find(id);
            if (hoaDon == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "TenKH", hoaDon.MaKH);
            ViewBag.MaNV = new SelectList(db.Nhanviens, "MaNV", "HoNV", hoaDon.MaNV);
            return View(hoaDon);
        }

        // POST: HoaDon/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaHD,MaKH,MaNV,NgayLapHD,NgayGiaoHang")] HoaDon hoaDon)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hoaDon).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "TenKH", hoaDon.MaKH);
            ViewBag.MaNV = new SelectList(db.Nhanviens, "MaNV", "HoNV", hoaDon.MaNV);
            return View(hoaDon);
        }

        // GET: HoaDon/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HoaDon hoaDon = db.HoaDons.Find(id);
            if (hoaDon == null)
            {
                return HttpNotFound();
            }
            return View(hoaDon);
        }

        // POST: HoaDon/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            HoaDon hoaDon = db.HoaDons.Find(id);
            db.HoaDons.Remove(hoaDon);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BachHoaMint/Views/HoaDon/Create.cshtml
@model BachHoaMint.Models.HoaDon

<h2>Thêm hóa đơn</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @*@Html.LabelFor(model => model.MaHD, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <p class="control-label col-md-2"><b>Mã hóa đơn</b></p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaHD, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaHD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.MaKH, "MaKH", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <p class="control-label col-md-2"><b>Khách hàng</b></p>
            <div class="col-md-10">
                @Html.DropDownList("MaKH", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.MaNV, "MaNV", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <p class="control-label col-md-2"><b>Nhân viên</b></p>
            <div class="col-md-10">
                @Html.DropDownList("MaNV", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.NgayLapHD, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <p class="control-label col-md-2"><b>Ngày lập hóa đơn</b></p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayLapHD, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayLapHD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.NgayGiaoHang, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <p class="control-label col-md-2"><b>Ngày giao hàng</b></p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayGiaoHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayGiaoHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở lại trang trước", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BachHoaMint/Views/HoaDon/Delete.cshtml
@model BachHoaMint.Models.HoaDon

<h2>Xóa hóa đơn</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @*@Html.DisplayNameFor(model => model.NgayLapHD)*@
            Ngày lập
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayLapHD)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.NgayGiaoHang)*@
            Ngày giao hàng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayGiaoHang)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.KhachHang.TenKH)*@
            Khách hàng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KhachHang.TenKH)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.Nhanvien.MaNV)*@
            Mã nhân viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nhanvien.MaNV)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Trở lại trang trước", "Index")
        </div>
    }
</div>

BachHoaMint/Views/HoaDon/Details.cshtml
@model BachHoaMint.Models.HoaDon

<h2>Chi tiết đơn hàng</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @*@Html.DisplayNameFor(model => model.NgayLapHD)*@
            Ngày lập
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayLapHD)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.NgayGiaoHang)*@
            Ngày giao hàng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayGiaoHang)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.KhachHang.TenKH)*@
            Khách hàng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KhachHang.TenKH)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.Nhanvien.MaNV)*@
            Mã nhân viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nhanvien.MaNV)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.MaHD }) |
    @Html.ActionLink("Trở lại trang trước", "Index")
</p>

BachHoaMint/Views/HoaDon/Edit.cshtml
@model BachHoaMint.Models.HoaDon

<h2>Sửa hóa đơn</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaHD)

        <div class="form-group">
            @*@Html.LabelFor(model => model.MaKH, "MaKH", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <p class="control-label col-md-2"><b>Khách hàng</b></p>
            <div class="col-md-10">
                @Html.DropDownList("MaKH", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.MaNV, "MaNV", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <p class="control-label col-md-2"><b>Mã nhân viên</b></p>
            <div class="col-md-10">
                @Html.DropDownList("MaNV", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.NgayLapHD, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <p class="control-label col-md-2"><b>Ngày lập</b></p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayLapHD, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayLapHD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.NgayGiaoHang, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <p class="control-label col-md-2"><b>Ngày giao hàng</b></p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayGiaoHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayGiaoHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở lại trang trước", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BachHoaMint/Views/HoaDon/Index.cshtml
@model IEnumerable<BachHoaMint.Models.HoaDon>

<h2>Danh sách hóa đơn</h2>

<p>
    @Html.ActionLink("Thêm hóa đơn", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Mã hóa đơn
            @*@Html.DisplayNameFor(model => model.MaHD)*@
        </th>
        <th>
            Ngày lập
            @*@Html.DisplayNameFor(model => model.NgayLapHD)*@
        </th>
        <th>
            Ngày giao hàng
            @*@Html.DisplayNameFor(model => model.NgayGiaoHang)*@
        </th>
        <th>
            Khách hàng
            @*@Html.DisplayNameFor(model => model.KhachHang.TenKH)*@
        </th>
        <th>
            Mã nhân viên
            @*@Html.DisplayNameFor(model => model.Nhanvien.MaNV)*@
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <a href="@Url.Action("Index", "CTHD", new {mahd = item.MaHD})">
                @Html.DisplayFor(modelItem => item.MaHD)
            </a>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgayLapHD)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgayGiaoHang)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.KhachHang.TenKH)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nhanvien.MaNV)
        </td>
        <td>
            @Html.ActionLink("Sửa", "Edit", new { id=item.MaHD }) |
            @Html.ActionLink("Chi tiết", "Details", new { id=item.MaHD }) |
            @Html.ActionLink("Xóa", "Delete", new { id=item.MaHD })
        </td>
    </tr>
}

</table>