BachHoaMint/Models/SanPham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BachHoaMint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string Donvitinh { get; set; }
        public Nullable<double> Dongia { get; set; }
        public Nullable<int> MaLoaiSP { get; set; }
        public string HinhSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
    }
}

BachHoaMint/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BachHoaMint.Models;
using System.IO;
using PagedList;

namespace BachHoaMint.Controllers
{
    public class SanPhamController : Controller
    {
        private QLBHEntities db = new QLBHEntities();

        // GET: SanPham
        public ActionResult Index(string sortOrder, int?page)
        {
            ViewBag.SortByName = String.IsNullOrEmpty(sortOrder) ? "ten_desc" : "";
            ViewBag.SortByPrice = (sortOrder == "dongia" ? "dongia_desc" : "dongia");
            ViewBag.SortOrder = sortOrder;
            var sanPhams = db.SanPhams.Include(s => s.LoaiSP);
            switch(sortOrder)
            {
                case "ten_desc":
                    sanPhams = sanPhams.OrderByDescending(s => s.TenSP);
                    break;
                case "dongia":
                    sanPhams = sanPhams.OrderBy(s => s.Dongia);
                    break;
                case "dongia_desc":
                    sanPhams = sanPhams.OrderByDescending(s => s.Dongia);
                    break;
                default:
                    sanPhams = sanPhams.OrderBy(s => s.TenSP);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(sanPhams.ToPagedList(pageNumber, pageSize));
        }

        // GET: SanPham/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // GET: SanPham/Create
        public ActionResult Create()
        {
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSPs, "MaLoaiSP", "TenLoaiSP");
            return View();
        }

        // POST: SanPham/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSP,TenSP,Donvitinh,Dongia,MaLoaiSP,HinhSP")] SanPham sanPham,
            HttpPostedFileBase HinhSP)
        {
            if (ModelState.IsValid)
            {
                if(HinhSP != null && HinhSP.ContentLength > 0)
                {
                    string filename = Path.GetFileName(HinhSP.FileName);
                    string path = Server.MapPath("~/Images/" + filename);
                    sanPham.HinhSP = "Images/" + filename;
                    HinhSP.SaveAs(path);
                }
                db.SanPhams.Add(sanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaLoaiSP = new SelectList(db.LoaiSPs, "MaLoaiSP", "TenLoaiSP", sanPham.MaLoaiSP);
            return View(sanPham);
        }

        // GET: SanPham/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSPs, "MaLoaiSP", "TenLoaiSP", sanPham.MaLoaiSP);
            return View(sanPham);
        }

        // POST: SanPham/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSP,TenSP,Donvitinh,Dongia,MaLoaiSP,HinhSP")] SanPham sanPham,
            HttpPostedFileBase HinhSP)
        {
            if (ModelState.IsValid)
            {
                if (HinhSP != null && HinhSP.ContentLength > 0)
                {
                    System.IO.File.Delete(Server.MapPath("~/" + sanPham.HinhSP));
                    string filename = Path.GetFileName(HinhSP.FileName);
                    string path = Server.MapPath("~/Images/" + filename);
                    sanPham.HinhSP = "Images/" + filename;
                    HinhSP.SaveAs(path);
                }
                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSPs, "MaLoaiSP", "TenLoaiSP", sanPham.MaLoaiSP);
            return View(sanPham);
        }

        // GET: SanPham/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: SanPham/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            db.SanPhams.Remove(sanPham);
            db.SaveChanges();
            if (sanPham.HinhSP != null)
                System.IO.File.Delete(Server.MapPath("~/" + sanPham.HinhSP));
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BachHoaMint/Views/SanPham/Create.cshtml
@model BachHoaMint.Models.SanPham

<h2>Thêm sản phẩm</h2>


@using (Html.BeginForm("Create", "SanPham", FormMethod.Post, new {enctype="multipart/form-data"})) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @*@Html.LabelFor(model => model.MaSP, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <p class="control-label col-md-2"><b>Mã</b></p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <p class="control-label col-md-2"><b>Tên</b></p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.Donvitinh, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <p class="control-label col-md-2"><b>Đơn vị tính</b></p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Donvitinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Donvitinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.Dongia, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <p class="control-label col-md-2"><b>Đơn giá</b></p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dongia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dongia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.MaLoaiSP, "MaLoaiSP", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <p class="control-label col-md-2"><b>Loại</b></p>
            <div class="col-md-10">
                @Html.DropDownList("MaLoaiSP", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoaiSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.HinhSP, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <p class="control-label col-md-2"><b>Hình ảnh</b></p>
            <div class="col-md-10">
                @Html.TextBox("HinhSP", "", new { type = "file" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về danh sách", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BachHoaMint/Views/SanPham/Delete.cshtml
@model BachHoaMint.Models.SanPham

<h2>Xóa sản phẩm này?</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên
            @*@Html.DisplayNameFor(model => model.TenSP)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSP)
        </dd>

        <dt>
            Đơn vị tính
            @*@Html.DisplayNameFor(model => model.Donvitinh)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Donvitinh)
        </dd>

        <dt>
            Đơn giá
            @*@Html.DisplayNameFor(model => model.Dongia)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dongia)
        </dd>

        <dt>
            Hình ảnh
            @*@Html.DisplayNameFor(model => model.HinhSP)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhSP)
        </dd>

        <dt>
            Loại
            @*@Html.DisplayNameFor(model => model.LoaiSP.TenLoaiSP)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSP.TenLoaiSP)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Trở về danh sách", "Index")
        </div>
    }
</div>

BachHoaMint/Views/SanPham/Details.cshtml
@model BachHoaMint.Models.SanPham
@using BachHoaMint.Models

@{
    ViewBag.Title = "Details";
}

<h2>Chi tiết sản phẩm</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @*@Html.DisplayNameFor(model => model.TenSP)*@
            Tên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSP)
        </dd>
        <dd>
            @Html.Image("../../" + Model.HinhSP, "", "350", "350")
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.LoaiSP.TenLoaiSP)*@
            Loại sản phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSP.TenLoaiSP)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.Donvitinh)*@
            Đơn vị tính
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Donvitinh)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.Dongia)*@
            Đơn giá

        </dt>

        <dd>
            @String.Format("{0:0,### VNĐ}", Model.Dongia)
        </dd>

        <!--<dt>
        <br />-->
        @*@Html.DisplayNameFor(model => model.HinhSP)*@
        @*Hình ảnh*@
        <!--</dt>-->
        @*<dd>
            @Html.Image("../../" + Model.HinhSP, "", "300", "300")
        </dd>*@

        <dt></dt>
        <dd>
            <br />
            <a class="btn btn-info" href="@Url.Action("AddToCart","GioHang", new {MaSP = Model.MaSP})">
                <span class="glyphicon glyphicon-shopping-cart"></span>Thêm vào giỏ hàng
            </a>
            <a class="btn btn-info" href="@Url.Action("Index", "Home")">
                Quay lại
            </a>
        </dd>

    </dl>
</div>
@*<div>
    @Html.ActionLink("Trở về danh sách", "Index")
</div>*@

BachHoaMint/Views/SanPham/Edit.cshtml
@model BachHoaMint.Models.SanPham
@using BachHoaMint.Models

<h2>Sửa thông tin sản phẩm</h2>


@using (Html.BeginForm("Edit", "SanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaSP)

                <div class="form-group">
                    @*@Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <p class="control-label col-md-2"><b>Tên</b></p>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @*@Html.LabelFor(model => model.Donvitinh, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <p class="control-label col-md-2"><b>Đơn vị tính</b></p>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Donvitinh, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Donvitinh, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @*@Html.LabelFor(model => model.Dongia, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <p class="control-label col-md-2"><b>Đơn giá</b></p>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Dongia, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Dongia, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @*@Html.LabelFor(model => model.MaLoaiSP, "MaLoaiSP", htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <p class="control-label col-md-2"><b>Loại</b></p>
                    <div class="col-md-10">
                        @Html.DropDownList("MaLoaiSP", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MaLoaiSP, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @*@Html.LabelFor(model => model.HinhSP, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <p class="control-label col-md-2"><b>Hình ảnh</b></p>
                    <div class="col-md-10">
                        @Html.Image("../../" + Model.HinhSP, "", "80", "100")
                        @Html.TextBox("HinhSP", "", new { type = "file" })
                        @Html.Hidden("HinhSP")
                    </div>
                </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về danh sách", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BachHoaMint/Views/SanPham/Index.cshtml
@model PagedList.IPagedList<BachHoaMint.Models.SanPham>
@using BachHoaMint.Models
@using PagedList.Mvc
<link rel="stylesheet" href="~/Content/PagedList.css"/>

<h2>Danh sách sản phẩm</h2>

<p>
    @Html.ActionLink("Thêm sản phẩm", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.TenSP)*@
            Mã sản phẩm
        </th>
        <th>
            Tên sản phẩm
            @Html.ActionLink(" ⇅ ", "Index", new {sortOrder = ViewBag.SortByName})
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Donvitinh)*@
            Đơn vị tính
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Dongia)*@
            Đơn giá
            @Html.ActionLink(" ⇅ ", "Index", new { sortOrder = ViewBag.SortByPrice })
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.HinhSP)*@
            Hình sản phẩm
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.LoaiSP.TenLoaiSP)*@
            Loại sản phẩm
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.MaSP)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.TenSP)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Donvitinh)
    </td>
    <td>
        @*@Html.DisplayFor(modelItem => item.Dongia)*@
        @String.Format("{0:0,###}", item.Dongia)
    </td>
    <td>
        @Html.Image("../../" + item.HinhSP, "", "40", "50")
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.LoaiSP.TenLoaiSP)
    </td>
    <td>
        @Html.ActionLink("Sửa", "Edit", new { id = item.MaSP }) |
        @Html.ActionLink("Chi tiết", "Details", new { id = item.MaSP }) |
        @Html.ActionLink("Xóa", "Delete", new { id = item.MaSP })
    </td>
</tr>
}

</table>
<div>
    Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index",
    new
        {
    page,
    sortOrder = ViewBag.SortOrder
    }))
</div>